const layers = {
  minor: document.querySelector('#minor-stars'), boundary: document.querySelector('#boundary-layer'),
  figures: document.querySelector('#figure-layer'), stars: document.querySelector('#star-layer'),
  messier: document.querySelector('#messier-layer'), answers: document.querySelector('#answer-layer'), markers: document.querySelector('#marker-layer')
};
const map = document.querySelector('#sky-map');
const skyWrap = document.querySelector('.sky-wrap');
const sidePanel = document.querySelector('#side-panel');
const toast = document.querySelector('#toast');

const zones = [
  { id:'summer', title:'Летний треугольник', constellation:'Лира · Лебедь · Геркулес', coords:'RA 18h–22h · DEC +10°–+50°', description:'Вега, Денеб и Альтаир создают самый удобный летний маршрут. Между ними — туманности и шаровые скопления, которые легко привязать к фигурам созвездий.',
    stars:[['Вега','α Lyr',445,168,6],['Шелиак','β Lyr',497,274,3],['Денеб','α Cyg',786,154,5],['Садр','γ Cyg',710,280,4],['Альтаир','α Aql',670,492,5],['Таразед','γ Aql',628,519,3],['Рас Альгети','α Her',260,299,4],['Арктур','α Boo',150,232,5]],
    figures:[['ЛИРА',430,102,'M445 168 L497 274 L457 320 L408 270 Z'],['ЛЕБЕДЬ',782,326,'M786 154 L710 280 L756 381 L670 492 M710 280 L631 330 M710 280 L810 351'],['ГЕРКУЛЕС',225,127,'M150 232 L223 196 L302 230 L332 324 L260 359 L193 305 Z'],['ОРЁЛ',612,582,'M628 519 L670 492 L721 531 M670 492 L661 585']],
    objects:[['M13','Большое скопление Геркулеса','шаровое скопление',310,270],['M92','Шаровое скопление','шаровое скопление',232,188],['M57','Кольцевая туманность','планетарная туманность',469,237],['M27','Гантель','планетарная туманность',653,286],['M15','Скопление Пегаса','шаровое скопление',975,211],['M39','Рассеянное скопление','рассеянное скопление',841,126]] },
  { id:'sagittarius', title:'Стрелец и Скорпион', constellation:'Стрелец · Скорпион · Змееносец', coords:'RA 16h–19h · DEC −40°–−5°', description:'Самая плотная часть Млечного Пути. Ищите «чайник» Стрельца и крючок Скорпиона — рядом собраны туманности и скопления Мессье.',
    stars:[['Антарес','α Sco',295,268,6],['Шаула','λ Sco',428,514,4],['Каус Аустралис','ε Sgr',762,486,4],['Нунки','σ Sgr',708,314,4],['Сабик','η Oph',497,170,4],['Аль Насл','γ Sgr',624,447,3]],
    figures:[['СКОРПИОН',176,170,'M295 268 L243 326 L218 394 L274 464 L355 441 L402 487 L428 514'],['СТРЕЛЕЦ',655,212,'M624 447 L690 393 L762 486 L802 406 L747 334 L708 314 L690 393 M747 334 L810 296'],['ЗМЕЕНОСЕЦ',438,91,'M497 170 L450 235 L475 314 L548 336 L592 271 L497 170']],
    objects:[['M6','Бабочка','рассеянное скопление',361,444],['M7','Скопление Птолемея','рассеянное скопление',406,480],['M8','Лагуна','эмиссионная туманность',646,440],['M20','Трёхраздельная','эмиссионная туманность',692,419],['M22','Шаровое скопление','шаровое скопление',710,356],['M24','Облако Стрельца','звёздное облако',757,371]] },
  { id:'spring', title:'Весенние галактики', constellation:'Большая Медведица · Гончие Псы · Волосы Вероники', coords:'RA 11h–14h · DEC +30°–+65°', description:'Здесь нет яркой Млечной Дороги — зато в телескопе одна за другой открываются далёкие галактики. Ориентир — ковш Большой Медведицы.',
    stars:[['Дубхе','α UMa',252,181,5],['Мерак','β UMa',336,254,4],['Алиот','ε UMa',468,302,5],['Мицар','ζ UMa',570,335,4],['Алькаид','η UMa',674,358,4],['Кор Кароли','α CVn',512,520,4],['Арктур','α Boo',787,584,6]],
    figures:[['БОЛЬШАЯ МЕДВЕДИЦА',242,99,'M252 181 L336 254 L437 220 L468 302 L570 335 L674 358 L744 413 M437 220 L468 302'],['ГОНЧИЕ ПСЫ',467,461,'M512 520 L585 477 L623 531'],['ВОЛОСЫ ВЕРОНИКИ',735,487,'M674 358 L735 442 L787 584 L853 495']],
    objects:[['M51','Водоворот','спиральная галактика',606,316],['M63','Подсолнух','спиральная галактика',559,393],['M94','Галактика Кошачий глаз','спиральная галактика',487,458],['M101','Вертушка','спиральная галактика',683,242],['M64','Чёрный глаз','спиральная галактика',640,468],['M106','Галактика','спиральная галактика',388,362]] },
  { id:'winter', title:'Зимние скопления', constellation:'Возничий · Близнецы · Большой Пёс', coords:'RA 5h–8h · DEC −25°–+45°', description:'Холодный сезон — лучшее время для ярких рассеянных скоплений. Двигайтесь от Капеллы к звёздам Близнецов и вниз, к Сириусу.',
    stars:[['Капелла','α Aur',342,150,6],['Менкалинан','β Aur',417,256,4],['Кастор','α Gem',665,185,5],['Поллукс','β Gem',633,278,5],['Бетельгейзе','α Ori',450,465,5],['Сириус','α CMa',770,585,6]],
    figures:[['ВОЗНИЧИЙ',266,89,'M342 150 L417 256 L366 344 L281 286 Z'],['БЛИЗНЕЦЫ',596,105,'M665 185 L633 278 L605 375 M665 185 L735 264 L761 360'],['БОЛЬШОЙ ПЁС',697,459,'M610 450 L688 516 L770 585 L850 526']],
    objects:[['M35','Рассеянное скопление','рассеянное скопление',687,307],['M36','Рассеянное скопление','рассеянное скопление',339,257],['M37','Рассеянное скопление','рассеянное скопление',381,290],['M38','Морская звезда','рассеянное скопление',293,277],['M41','Рассеянное скопление','рассеянное скопление',743,545],['M46','Рассеянное скопление','рассеянное скопление',622,570]] }
];

let currentZone = 0, mode = 'learn', currentTarget = null, answer = null, marker = null, score = 0, streak = 0, toastTimer;
const el = (name, attrs={}, text='') => { const node=document.createElementNS('http://www.w3.org/2000/svg',name); Object.entries(attrs).forEach(([k,v])=>node.setAttribute(k,v)); if(text)node.textContent=text; return node; };
const zone = () => zones[currentZone];
const objectFrom = (item) => ({id:item[0],name:item[1],type:item[2],x:item[3],y:item[4]});

function setView(name){
  ['home','tour','atlas'].forEach((view)=>{const section=document.querySelector(`#${view}-view`);section.hidden=view!==name;section.classList.toggle('is-active',view===name);});
  window.scrollTo({top:0,behavior:'auto'});
}
function randomZone(){let next=currentZone;if(zones.length>1){while(next===currentZone)next=Math.floor(Math.random()*zones.length);}currentZone=next;}
function renderMinor(){layers.minor.innerHTML='';for(let i=0;i<115;i++){const x=((i*137.5)%1160)+20,y=((i*71.3)%720)+15;layers.minor.append(el('circle',{class:'minor-star',cx:x,cy:y,r:[.6,.8,1,1.2][i%4],opacity:.22+(i%5)*.1}));}}
function renderMap(){
  const data=zone(); layers.boundary.innerHTML='';layers.figures.innerHTML='';layers.stars.innerHTML='';layers.messier.innerHTML='';layers.answers.innerHTML='';layers.markers.innerHTML='';
  data.figures.forEach(([name,x,y,path],index)=>{layers.boundary.append(el('path',{class:'constellation-boundary',d:path.replaceAll('M','M').replaceAll(' L',' L')}));layers.figures.append(el('path',{class:'constellation-figure',d:path}));layers.figures.append(el('text',{class:'constellation-label',x,y},name));});
  data.stars.forEach(([name,latin,x,y,r])=>{const g=el('g',{});g.append(el('circle',{class:'bright-star',cx:x,cy:y,r:r+4,opacity:.14}));g.append(el('circle',{class:'bright-star',cx:x,cy:y,r}));g.append(el('circle',{class:'bright-star-core',cx:x,cy:y,r:Math.max(1.4,r/3)}));g.append(el('text',{class:'star-name',x:x+11,y:y-7},name));g.append(el('text',{class:'star-sub',x:x+11,y:y+9},latin));layers.stars.append(g);});
  if(mode==='learn')data.objects.forEach((item)=>{const object=objectFrom(item),g=el('g',{class:'messier-object',role:'button',tabindex:'0','aria-label':`${object.id}, ${object.name}`});g.append(el('circle',{class:'object-halo',cx:object.x,cy:object.y,r:19}));g.append(el('circle',{class:'object-core',cx:object.x,cy:object.y,r:5.5}));g.append(el('line',{class:'object-guide',x1:object.x+7,y1:object.y-4,x2:object.x+25,y2:object.y-18}));g.append(el('text',{class:'object-id',x:object.x+29,y:object.y-20},object.id));g.append(el('text',{class:'object-name',x:object.x+29,y:object.y-7},object.name));g.addEventListener('click',(event)=>{event.stopPropagation();showToast(`${object.id} — ${object.name}, ${object.type}.`);});layers.messier.append(g);});
  if(mode==='practice'&&answer){const ringClass=answer.correct?'answer-ring':'answer-ring is-wrong';layers.answers.append(el('circle',{class:ringClass,cx:currentTarget.x,cy:currentTarget.y,r:25}));}
  if(marker){layers.markers.append(el('circle',{class:'placed-marker',cx:marker.x,cy:marker.y,r:10}));layers.markers.append(el('text',{class:'placed-marker-label',x:marker.x,y:marker.y+25},currentTarget.id));}
  updateLayers();
}
function renderLearnPanel(){const points=zone().objects.map((item)=>{const object=objectFrom(item);return `<div class="zone-point"><span class="zone-point__id">${object.id}</span><span><strong>${object.name}</strong><small>${object.type}</small></span></div>`;}).join('');sidePanel.innerHTML=`<p class="overline">Открытый атлас</p><h2>${zone().title}</h2><p class="intro">Участок можно изучать сколько угодно: новая карта выбирается случайно, а подписи остаются на месте.</p><div class="zone-points">${points}</div><button class="primary-button" data-action="next-learn" type="button">Следующий случайный участок <span>→</span></button><button class="secondary-button" data-action="start-practice" type="button">Проверить себя без подписей</button>`;}
function renderPracticePanel(){const result=answer?`<p class="answer-copy ${answer.correct?'':'is-wrong'}">${answer.correct?'Точно! Вы нашли объект по звёздным ориентирам.':'Почти. Окружность на карте показывает точное место объекта.'}</p>`:`<p class="answer-copy">Ориентируйтесь по фигурам созвездий и ярким звёздам. Метка появится после клика.</p>`;sidePanel.innerHTML=`<p class="overline">Бесконечная тренировка</p><h2>Поставьте метку<br />на карте</h2><p class="intro">Карта обновляется случайными участками. Названия Мессье скрыты.</p><div class="practice-target"><span class="practice-target__label">Найдите объект</span><strong>${currentTarget.id}</strong><span>${currentTarget.name}<br />${currentTarget.type}</span></div><div class="score-row"><span>Точно найдено</span><b>${score}</b><span>Серия: ${streak}</span></div>${result}<button class="primary-button" data-action="next-practice" type="button">${answer?'Следующий объект →':'Нужна метка на карте'}</button><button class="secondary-button" data-action="new-map" type="button">Случайная карта</button>`;const button=sidePanel.querySelector('[data-action="next-practice"]');if(!answer)button.disabled=true;}
function updateScreen(){const data=zone();document.querySelector('#atlas-title').textContent=data.title;document.querySelector('#atlas-overline').textContent=mode==='learn'?'Открытый атлас · случайный участок':'Тренировка · случайный участок';document.querySelector('#atlas-description').textContent=data.description;document.querySelector('#map-coordinates').textContent=data.coords;document.querySelector('#mode-label').textContent=mode==='learn'?'Открытый атлас':'Бесконечная тренировка';document.querySelector('#mode-dot').style.background=mode==='learn'?'#1d5776':'#c85e4e';document.querySelector('#map-instruction').textContent=mode==='learn'?'Нажмите на объект для карточки':'Выберите положение объекта на карте';skyWrap.classList.toggle('is-practice',mode==='practice');renderMap();mode==='learn'?renderLearnPanel():renderPracticePanel();}
function start(modeName){mode=modeName;randomZone();answer=null;marker=null;if(mode==='practice')setTarget();setView('atlas');updateScreen();}
function setTarget(){const items=zone().objects.map(objectFrom);let target=items[Math.floor(Math.random()*items.length)];if(items.length>1&&currentTarget){while(target.id===currentTarget.id)target=items[Math.floor(Math.random()*items.length)];}currentTarget=target;}
function nextPractice(){answer=null;marker=null;if(Math.random()>.55)randomZone();setTarget();updateScreen();}
function nextMap(){randomZone();answer=null;marker=null;if(mode==='practice')setTarget();updateScreen();showToast('Открыта новая случайная карта.');}
function mapPoint(event){const box=map.getBoundingClientRect();return{x:(event.clientX-box.left)/box.width*1200,y:(event.clientY-box.top)/box.height*760};}
function attempt(event){if(mode!=='practice'||answer)return;marker=mapPoint(event);const distance=Math.hypot(marker.x-currentTarget.x,marker.y-currentTarget.y);answer={correct:distance<43};if(answer.correct){score++;streak++;showToast(`Верно — ${currentTarget.id} найден.`);}else{streak=0;showToast(`Точный ответ отмечен окружностью.`);}updateScreen();}
function updateLayers(){layers.figures.style.display=document.querySelector('#figures-toggle').checked?'':'none';layers.boundary.style.display=document.querySelector('#figures-toggle').checked?'':'none';layers.stars.style.display=document.querySelector('#stars-toggle').checked?'':'none';map.querySelector('rect:nth-of-type(2)').style.display=document.querySelector('#grid-toggle').checked?'':'none';}
function showToast(text){toast.textContent=text;toast.classList.add('is-visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('is-visible'),3300);}
document.addEventListener('click',(event)=>{const action=event.target.closest('[data-action]')?.dataset.action;if(!action)return;if(action==='home')setView('home');if(action==='open-tour')setView('tour');if(action==='start-learn')start('learn');if(action==='start-practice')start('practice');if(action==='next-learn'||action==='new-map')nextMap();if(action==='next-practice')nextPractice();});
map.addEventListener('click',attempt);['figures-toggle','stars-toggle','grid-toggle'].forEach((id)=>document.querySelector(`#${id}`).addEventListener('change',updateLayers));
renderMinor();updateScreen();
